title: UH Class Critics
description: By Ana Araujo, Johnny Ho, Zi Jun Huang, Steven Le, and John Suelen
google_analytics:
show_downloads: false
theme: jekyll-theme-midnight
github:
  is_project_page: true
  repository_url: https://github.com/uh-class-critics/uh-class-critics.github.io
gems:
  - jekyll-mentions
